from enum import StrEnum


class InternalStatus(StrEnum):
    NOT_REVIEWED = "NOT_REVIEWED"
    SMART_REJECTED = "SMART_REJECTED"
    SMART_NOT_REJECTED = "SMART_NOT_REJECTED"
    NEEDS_HUMAN_REVIEW = "NEEDS_HUMAN_REVIEW"
    UNSUPPORTED_SOURCE = "UNSUPPORTED_SOURCE"
    ERROR = "ERROR"
    SYNC_ERROR = "SYNC_ERROR"


class PriorityBucket(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    REVIEW_UNKNOWN = "REVIEW_UNKNOWN"


class RuleSetStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"


class RuleGroupType(StrEnum):
    GATE = "GATE"
    OVERRIDE = "OVERRIDE"
    SCORING = "SCORING"
    REVIEW = "REVIEW"
    INFO = "INFO"


class RuleType(StrEnum):
    REJECT_GATE = "REJECT_GATE"
    PASS_GATE = "PASS_GATE"
    OVERRIDE_PASS = "OVERRIDE_PASS"
    NEEDS_REVIEW_GATE = "NEEDS_REVIEW_GATE"
    SCORE_BONUS = "SCORE_BONUS"
    SCORE_PENALTY = "SCORE_PENALTY"
    INFO_ONLY = "INFO_ONLY"


class RuleOperator(StrEnum):
    EXISTS = "EXISTS"
    NOT_EXISTS = "NOT_EXISTS"
    EQUALS = "EQUALS"
    NOT_EQUALS = "NOT_EQUALS"
    IN = "IN"
    NOT_IN = "NOT_IN"
    CONTAINS = "CONTAINS"
    NOT_CONTAINS = "NOT_CONTAINS"
    CONTAINS_ANY = "CONTAINS_ANY"
    FUZZY_MATCH = "FUZZY_MATCH"
    FUZZY_IN = "FUZZY_IN"
    REGEX_MATCH = "REGEX_MATCH"
    GREATER_THAN = "GREATER_THAN"
    GREATER_THAN_OR_EQUAL = "GREATER_THAN_OR_EQUAL"
    LESS_THAN = "LESS_THAN"
    LESS_THAN_OR_EQUAL = "LESS_THAN_OR_EQUAL"
    BETWEEN = "BETWEEN"
    DURATION_AT_LEAST = "DURATION_AT_LEAST"


class MissingDataPolicy(StrEnum):
    NEEDS_REVIEW = "NEEDS_REVIEW"
    REJECT = "REJECT"
    IGNORE = "IGNORE"


class AIAnalysisStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    FAILED_SCHEMA_VALIDATION = "FAILED_SCHEMA_VALIDATION"
    FAILED_FINAL = "FAILED_FINAL"


class RecruiterDecision(StrEnum):
    RECRUITER_APPROVED_FOR_NEXT_STEP = "RECRUITER_APPROVED_FOR_NEXT_STEP"
    RECRUITER_REJECTED = "RECRUITER_REJECTED"
    RECRUITER_NEEDS_MORE_INFO = "RECRUITER_NEEDS_MORE_INFO"
    RECRUITER_CONTACT_CANDIDATE = "RECRUITER_CONTACT_CANDIDATE"


class NoteType(StrEnum):
    AI_SCREENING_NOTE = "AI_SCREENING_NOTE"
    RECRUITER_NOTE = "RECRUITER_NOTE"
    SYSTEM_NOTE = "SYSTEM_NOTE"


class ActorType(StrEnum):
    USER = "USER"
    SYSTEM = "SYSTEM"
    WORKER = "WORKER"


class RankingScope(StrEnum):
    JOB = "JOB"
    JOB_AND_RUN = "JOB_AND_RUN"
    JOB_AND_RULESET = "JOB_AND_RULESET"

